---
- hosts: all
  tasks:
    - name: Redémarrer Apache2
      become: yes
      become_user: ansible
      systemd:
        name: apache2
        state: restarted
      when: ansible_facts.services['apache2.service'] is defined
