---
- name: Recherche des fichiers les plus volumineux
  hosts: all
  become: true
  gather_facts: false

  tasks:
    - name: Trouver les fichiers les plus volumineux
      shell: find / -type f -exec du -h {} + | sort -h -r | head -n 10
      register: largest_files

    - name: Afficher le résultat
      debug:
        var: largest_files.stdout_lines
