---
- name: Recherche du fichier le plus volumineux
  hosts: all
  become: true
  gather_facts: false

  tasks:
    - name: Trouver le fichier le plus volumineux
      shell: du -a / | sort -n -r | head -n 1
      register: largest_file

    - name: Afficher le résultat
      debug:
        var: largest_file.stdout_lines
